# Generated by Django 5.2.4 on 2025-10-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('internship', 'Internship')], default='full-time', max_length=20),
        ),
        migrations.AlterField(
            model_name='career',
            name='plan_required',
            field=models.CharField(blank=True, choices=[('project', 'Project Pass'), ('premium', 'Premium Pass')], max_length=20, null=True),
        ),
    ]
