# Generated by Django 5.2.4 on 2025-10-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_career_job_type_alter_career_plan_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='assessment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
