# Generated by Django 5.2.4 on 2025-10-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_jobapplication_assessment_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
