# Generated by Django 5.2.4 on 2025-10-09 15:34

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(default=datetime.datetime(2025, 10, 16, 15, 34, 23, 107674, tzinfo=datetime.timezone.utc))),
                ('target', models.CharField(default='all', max_length=50)),
            ],
        ),
    ]
