# Generated by Django 5.2.4 on 2025-10-11 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 18, 19, 35, 5, 740555, tzinfo=datetime.timezone.utc)),
        ),
    ]
