# Generated by Django 5.2.4 on 2025-10-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_offer_end_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
