# Generated by Django 5.2.4 on 2025-07-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_mobile_number_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership_status',
            field=models.CharField(default='Free', max_length=50),
        ),
    ]
