# Generated by Django 5.2.4 on 2025-08-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_membership_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cointransaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
