# Generated by Django 5.2.4 on 2025-08-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_liveproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveproject',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='liveproject',
            name='reviewer_message',
        ),
        migrations.AlterField(
            model_name='liveproject',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
