# Generated by Django 5.2.4 on 2025-08-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_created_at_cointransaction_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cointransaction',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
