# Generated by Django 5.2.4 on 2025-08-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_timestamp_cointransaction_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cointransaction',
            old_name='amount',
            new_name='coins',
        ),
    ]
