# Generated by Django 5.2.4 on 2025-09-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_amount_cointransaction_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptransaction',
            name='plan',
            field=models.CharField(choices=[('project', 'Project Pass'), ('premium', 'Premium Pass')], max_length=50),
        ),
        migrations.AlterField(
            model_name='membershiptransaction',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membershiptransaction',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CoinWallet',
        ),
    ]
