# Generated by Django 5.2.4 on 2025-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_membershiptransaction_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='membership_status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_plan',
            field=models.CharField(choices=[('free', 'Free'), ('project', 'Project'), ('premium', 'Premium')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='membership_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='membership_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
