# Generated by Django 5.2.4 on 2025-09-29 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customuser_membership_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='current_plan',
            field=models.CharField(default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='membershiptransaction',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershiptransaction',
            name='plan',
            field=models.CharField(choices=[('project', 'Project Pass'), ('premium', 'Premium Pass')], max_length=20),
        ),
        migrations.AlterField(
            model_name='membershiptransaction',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='membershiptransaction',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershiptransaction',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
