# Generated by Django 5.2.4 on 2025-09-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_current_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_plan',
            field=models.CharField(default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='membershiptransaction',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
