# Generated by Django 5.2.4 on 2025-09-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_current_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_plan',
            field=models.CharField(default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='membershiptransaction',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershiptransaction',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
