# Generated by Django 5.2.4 on 2025-09-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_current_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('download_url', models.CharField(max_length=255)),
                ('is_free', models.BooleanField(default=False)),
                ('plan_required', models.CharField(blank=True, choices=[('project', 'Project Pass'), ('premium', 'Premium Pass')], max_length=20, null=True)),
            ],
        ),
    ]
