# Generated by Django 5.2.4 on 2025-10-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_liveworkproject_liveworksubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveworkproject',
            name='coins_reward',
        ),
        migrations.RemoveField(
            model_name='liveworksubmission',
            name='assessment_link',
        ),
        migrations.AlterField(
            model_name='liveworksubmission',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='liveworksubmission',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
