# Generated by Django 5.2.4 on 2025-10-02 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_liveworkproject_coins_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveworkproject',
            name='coins_reward',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='liveworksubmission',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='liveworksubmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
