# Generated by Django 5.2.4 on 2025-10-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_liveworkproject_coins_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveworkproject',
            name='coins_reward',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='liveworksubmission',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='liveworksubmission',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
