# Generated by Django 5.2.4 on 2025-10-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_liveworkproject_coins_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveworkproject',
            name='plan_required',
            field=models.CharField(choices=[('free', 'Free'), ('project', 'Project'), ('premium', 'Premium')], default='premium', max_length=50),
        ),
    ]
