# Generated by Django 5.2.4 on 2025-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_liveworkproject_plan_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveworkproject',
            name='plan_required',
            field=models.CharField(default='premium', max_length=50),
        ),
    ]
