# Generated by Django 5.2.4 on 2025-10-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_liveworkproject_plan_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveworkproject',
            name='plan_required',
            field=models.CharField(choices=[('free', 'Free'), ('project', 'Project'), ('premium', 'Premium')], default='premium', max_length=50),
        ),
    ]
