# Generated by Django 5.2.4 on 2025-10-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_customuser_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, help_text='Enter your skills separated by commas, e.g., Python, Django, SQL', null=True),
        ),
    ]
